"""no description in alternative table

Revision ID: 55118d541dab
Revises: 6b499b69f9a8
Create Date: 2025-01-29 09:07:35.652245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55118d541dab'
down_revision = '6b499b69f9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alternative', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alternative', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=256), nullable=True))

    # ### end Alembic commands ###
